import { copyFile, cp, mkdir, readdir, stat, writeFile } from "node:fs/promises";
import { join } from "node:path";

const root = process.cwd();
const siteDir = join(root, "site");

async function pathExists(path) {
  try {
    await stat(path);
    return true;
  } catch {
    return false;
  }
}

async function copyMarkdownDirectory(source, target) {
  if (!(await pathExists(source))) {
    return;
  }

  await mkdir(target, { recursive: true });
  const entries = await readdir(source, { withFileTypes: true });

  await Promise.all(
    entries
      .filter((entry) => entry.isFile() && entry.name.endsWith(".md"))
      .map((entry) => copyFile(join(source, entry.name), join(target, entry.name)))
  );
}

async function main() {
  await mkdir(siteDir, { recursive: true });
  await copyMarkdownDirectory(join(root, "docs"), join(siteDir, "docs"));
  await copyMarkdownDirectory(join(root, "benchmark"), join(siteDir, "benchmark"));
  await writeFile(join(siteDir, ".nojekyll"), "");

  const coverageExists = await pathExists(join(siteDir, "coverage", "index.html"));
  const typedocExists = await pathExists(join(siteDir, "typedoc", "index.html"));
  const slowExists = await pathExists(join(siteDir, "slow", "index.html"));
  const optimizedExists = await pathExists(join(siteDir, "optimized", "index.html"));

  if (await pathExists(join(root, "LICENSE"))) {
    await cp(join(root, "LICENSE"), join(siteDir, "LICENSE"));
  }

  await writeFile(
    join(siteDir, "index.html"),
    `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Frontend Performance Lab</title>
    <style>
      :root {
        color-scheme: light dark;
        font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
        background: #f6f7fb;
        color: #172033;
      }
      body {
        margin: 0;
      }
      main {
        max-width: 1120px;
        margin: 0 auto;
        padding: 48px 20px;
      }
      h1 {
        margin: 0 0 12px;
        font-size: clamp(2rem, 4vw, 4rem);
        line-height: 1;
      }
      p {
        max-width: 760px;
        color: #4d5a73;
        line-height: 1.65;
      }
      .grid {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
        gap: 16px;
        margin-top: 28px;
      }
      a {
        display: block;
        min-height: 120px;
        padding: 20px;
        border: 1px solid #d7dce8;
        border-radius: 8px;
        color: inherit;
        text-decoration: none;
        background: #fff;
      }
      a:hover,
      a:focus-visible {
        outline: 3px solid #34a0a4;
        outline-offset: 2px;
      }
      strong {
        display: block;
        margin-bottom: 8px;
        font-size: 1.1rem;
      }
      span {
        color: #63708a;
        line-height: 1.5;
      }
      @media (prefers-color-scheme: dark) {
        :root {
          background: #111827;
          color: #eef3ff;
        }
        p,
        span {
          color: #bac5dc;
        }
        a {
          background: #182235;
          border-color: #2d3a52;
        }
      }
    </style>
  </head>
  <body>
    <main>
      <h1>Frontend Performance Lab</h1>
      <p>
        A portfolio-grade React performance case study with intentionally slow and optimized implementations,
        benchmark instrumentation, coverage, TypeDoc output, and reproducible measurement notes.
      </p>
      <section class="grid" aria-label="Site sections">
        ${slowExists ? '<a href="./slow/"><strong>Slow App</strong><span>Baseline implementation with deliberate render, bundle, and list pressure.</span></a>' : ""}
        ${optimizedExists ? '<a href="./optimized/"><strong>Optimized App</strong><span>The same UI with targeted memoization, virtualization, lazy loading, and state locality.</span></a>' : ""}
        ${coverageExists ? '<a href="./coverage/"><strong>Coverage</strong><span>HTML coverage generated by Vitest and the V8 provider.</span></a>' : ""}
        ${typedocExists ? '<a href="./typedoc/"><strong>TypeDoc</strong><span>Documentation for benchmark, profiling, data, and performance helper APIs.</span></a>' : ""}
        <a href="./docs/results-before-after.md"><strong>Results Template</strong><span>Before and after metrics table with placeholders for manual measurements.</span></a>
        <a href="./benchmark/README.md"><strong>Benchmark Protocol</strong><span>Reusable scenarios and measurement flow for both apps.</span></a>
      </section>
    </main>
  </body>
</html>
`
  );
}

await main();
